#!/usr/bin/env bash
# Generate version.ts with repository information
#
# In CI release builds (RELEASE_TAG set), use the tag directly to avoid false
# "-dirty" stamps from CI artifacts (node_modules, build outputs, etc.).
# Local builds use jj commit metadata with dirty detection for accurate dev info.

set -euo pipefail

VERSION_FILE="src/version.ts"
TMP_FILE=$(mktemp)
trap 'rm -f "$TMP_FILE"' EXIT

export JJ_CONFIG_TOML=${JJ_CONFIG_TOML:-$'ui.paginate="never"\nui.color="never"'}

# MUX_GIT_COMMIT overrides the commit stamp (e.g. Nix builds where .git is
# unavailable in the sandbox but the revision is known to the flake).
# Namespaced deliberately: plain GIT_COMMIT is exported ambiently by some CI
# systems (Jenkins) and could pair a stale commit with HEAD's describe.
GIT_COMMIT="${MUX_GIT_COMMIT:-$(jj log -r @- --no-graph -T 'commit_id.short()' 2>/dev/null || jj log -r @ --no-graph -T 'commit_id.short()' 2>/dev/null || git rev-parse --short HEAD 2>/dev/null || echo "unknown")}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ -n "${RELEASE_TAG:-}" ]; then
  # CI release: use the authoritative tag, never dirty
  GIT_DESCRIBE="$RELEASE_TAG"
  echo "Release build: using RELEASE_TAG=${RELEASE_TAG}"
else
  # Local/dev build: use jj commit metadata with dirty detection.
  GIT_DESCRIBE="$GIT_COMMIT"

  # Debug output for dirty builds.
  if jj root >/dev/null 2>&1; then
    DIRTY_FILES=$(jj diff --name-only 2>/dev/null || true)
    if [ -n "$DIRTY_FILES" ]; then
      GIT_DESCRIBE="${GIT_DESCRIBE}-dirty"
      echo "⚠️  Jj working copy has changes; version will be stamped with '-dirty'."
      echo "Tracked dirty files:"
      echo "  - ${DIRTY_FILES//$'\n'/$'\n  - '}"
    fi
  fi

  # Keep dev builds stable when VCS metadata is unchanged so `make start` can
  # attach to an already-running Vite server without triggering avoidable HMR.
  if [ -f "$VERSION_FILE" ]; then
    EXISTING_GIT_COMMIT=$(sed -n 's/^  git_commit: "\(.*\)",$/\1/p' "$VERSION_FILE")
    EXISTING_GIT_DESCRIBE=$(sed -n 's/^  git_describe: "\(.*\)",$/\1/p' "$VERSION_FILE")
    EXISTING_BUILD_TIME=$(sed -n 's/^  buildTime: "\(.*\)",$/\1/p' "$VERSION_FILE")

    if [ "$EXISTING_GIT_COMMIT" = "$GIT_COMMIT" ] && [ "$EXISTING_GIT_DESCRIBE" = "$GIT_DESCRIBE" ] && [ -n "$EXISTING_BUILD_TIME" ]; then
      TIMESTAMP="$EXISTING_BUILD_TIME"
    fi
  fi
fi

cat >"$TMP_FILE" <<EOF
// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually

export const VERSION = {
  git_commit: "${GIT_COMMIT}",
  git_describe: "${GIT_DESCRIBE}",
  buildTime: "${TIMESTAMP}",
};
EOF

if [ -f "$VERSION_FILE" ] && cmp -s "$TMP_FILE" "$VERSION_FILE"; then
  echo "version.ts already up to date: ${GIT_DESCRIBE} (${GIT_COMMIT}) at ${TIMESTAMP}"
  exit 0
fi

mv "$TMP_FILE" "$VERSION_FILE"
trap - EXIT

echo "Generated version.ts: ${GIT_DESCRIBE} (${GIT_COMMIT}) at ${TIMESTAMP}"
