export {
  CREATE_DELEGATION_ROLLUPS_TABLE_SQL,
  CREATE_EVENTS_TABLE_SQL,
  CREATE_INGEST_META_TABLE_SQL,
  CREATE_PROVIDER_QUOTA_SNAPSHOTS_TABLE_SQL,
  CREATE_WATERMARK_TABLE_SQL,
} from "@/common/analytics/schemaSql";
